In [1]:
import numpy as np
import time

In [3]:
#execution performance
size = 10_000_000
#time
#python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seconds")
#numpy array
np_arr = np.array(py_list)
start = time.time()
#vectorization
sq_array = np_arr ** 2
end = time.time()
print(f"numpy array time = {end-start} seconds")


python list time = 2.5035316944122314 seconds
numpy array time = 0.07552719116210938 seconds


In [5]:
#memory
import sys
print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"numpy array size = {np_arr.nbytes} bytes")

python list size = 800000560000000 bytes
numpy array size = 80000000 bytes


In [13]:
# create - from lists
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.dtype, arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

arr2D = np.array([[1,2,3],[4,5,6],[2,3,4]])
print(arr2D, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [2 3 4]] (3, 3)


In [21]:
# create arrays
arr1 = np.zeros((3,3), dtype = "int64")
print(arr1, arr1.shape)

arr2 = np.ones((3,3))
print(arr2, arr2.shape)

arr3 = np.full((3,4), 100)
print(arr3, arr3.shape)

arr4 = np.arange(1,4)
print(arr4, arr4.shape)

arr5 = np.eye(3)
print(arr5, arr5.shape)

arr6 = np.linspace(0,100,4)
print(arr6, arr6.shape)


[[0 0 0]
 [0 0 0]
 [0 0 0]] (3, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (3, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[1 2 3] (3,)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[  0.          33.33333333  66.66666667 100.        ] (4,)
[1. 2. 3. 4. 5.]


In [25]:
# Properties
arr = np.array([1,2,3,4,5,5])
print(arr.shape)
print(arr.size)
print(arr.ndim)
float_arr = arr.astype(np.float64)
print(float_arr)

(6,)
6
1
[1. 2. 3. 4. 5. 5.]


In [28]:
# Reshaping array
arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped)

flat = arr.flatten()
print(flat)


[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [33]:
# Indexing
arr = np.array([1,2,3,4,5])
arr1 = np.array([[1,2,3],[4,5,6]])

print(arr[0])
print(arr1[0][2])

# Fancy Indexing
ar = np.array([1,2,3,4,5])
idx = [0, 1, 3]

print(ar[idx])

# Boolean Indexing
ar = np.array([1,2,3,4,5])
print(ar[ar > 3])



1
3
[1 2 4]
[4 5]


In [38]:
# Slicing
arr = np.array([1,2,3,4,5])
print(arr[::2])

[1 3 5]


In [42]:
# Copy vs View
nums = [1,2,3,4.5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200
print(sub_list)
print(nums)

arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:3].copy()
sub_arr[0] = 200
print(sub_arr)
print(arr)

[2, 3]
[200, 3]
[1, 2, 3, 4.5]
[200   3]
[1 2 3 4 5]


In [46]:
# Data Types
arr = np.array([1,2,3,4,5])
print(arr.dtype)

int64


In [52]:
# Multi-dimensional array 2D array
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)
print(np.sum(arr2D))

sum_col = np.sum(arr2D, axis = 0)
print(sum_col)

sum_row = np.sum(arr2D, axis = 1)
print(sum_row)

print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [58]:
# 3D array
arr = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]]) #2 x 3 x 2
print(arr, arr.shape)
print(arr[1,1,0])
print(arr[:,0,:])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[1 2]
 [7 8]]


In [60]:
# Broadcasting
arr = np.array([1, 2, 3])
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr + arr2D)


[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [64]:
# Vector Normalization z-score
arr = np.array([[1, 2], [3, 4]])

mean = np.mean(arr) # (1+2+3+4)/4 = 2.5
std_dev = np.std(arr) # result = ((1-2.5)**2 + (2-2.5)**2 + (3-2.5)**2 + (4-2.5)**2)/4
# then square root result
norm_arr = (arr - mean) / std_dev
print(norm_arr)


[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [68]:
# Mathematical functions
#aggregation func
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr)) # std_dev without square root

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [73]:
# power functions
arr = np.array([1, 2, 3, 4, 5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3))


[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [75]:
# log functions
arr = np.array([1, 2, 3, 4, 5])
print(np.log(arr)) # base e
print(np.log2(arr))
print(np.exp(arr)) # e power x


[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [80]:
# rounding function
print(np.round(3.94))
print(np.ceil(3.94))
print(np.floor(3.94))
print(np.trunc(3.94))

arr = np.array([1, 2, 2, 2, 5])
print(np.unique(arr))
arr = np.array([1, 2, 3, 0, 1])
print(np.sort(arr))
arr = np.array([1, 2, 3, -4, -5])
print(np.abs(arr))



4.0
4.0
3.0
3.0
[1 2 5]
[0 1 1 2 3]
[1 2 3 4 5]
